#!/usr/bin/env bash
set -euo pipefail

# generate_env.sh
# Generates backend/.env from environment variables on the server.
# Usage: run this script on the VPS after you have set the required environment variables
# Example: export DB_USER=myuser; export DB_PASS=mypass; ./scripts/generate_env.sh

TARGET="./backend/.env"

required() {
  local varname="$1"
  if [ -z "${!varname:-}" ]; then
    echo "ERROR: environment variable '$varname' is not set" >&2
    exit 1
  fi
}

required DB_HOST
required DB_PORT
required DB_USER
required DB_PASS
required DB_NAME
required JWT_SECRET

cat > "$TARGET" <<EOF
# Auto-generated by scripts/generate_env.sh - DO NOT COMMIT
DB_HOST="${DB_HOST}"
DB_PORT="${DB_PORT}"
DB_USER="${DB_USER}"
DB_PASS="${DB_PASS}"
DB_NAME="${DB_NAME}"

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"

JWT_SECRET="${JWT_SECRET}"
JWT_EXPIRES_IN="${JWT_EXPIRES_IN:-24h}"

PORT=${PORT:-3000}
HOST="${HOST:-0.0.0.0}"
NODE_ENV="${NODE_ENV:-production}"
LOG_LEVEL="${LOG_LEVEL:-info}"

# Firebase (optional)
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-}"
API_BASE_URL="${API_BASE_URL:-http://localhost:${PORT:-3000}}"
EOF

echo "Generated $TARGET"
