#!/usr/bin/env bash
set -euo pipefail

# generate_env.sh
# Generates both a project root `.env` and `backend/.env` from environment variables on the server.
# Usage: run this script on the VPS after you have set the required environment variables
# Example: export DB_USER=myuser; export DB_PASS=mypass; ./scripts/generate_env.sh

ROOT_ENV_FILE="./.env"
BACKEND_ENV_FILE="./backend/.env"

required() {
  local varname="$1"
  if [ -z "${!varname:-}" ]; then
    echo "ERROR: environment variable '$varname' is not set" >&2
    exit 1
  fi
}

required DB_HOST
required DB_PORT
required DB_USER
required DB_PASS
required DB_NAME
required JWT_SECRET

# Defaults for optional envs
JWT_EXPIRES_IN="${JWT_EXPIRES_IN:-24h}"
PORT="${PORT:-3000}"
HOST="${HOST:-0.0.0.0}"
NODE_ENV="${NODE_ENV:-production}"
LOG_LEVEL="${LOG_LEVEL:-info}"
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-}"
API_BASE_URL="${API_BASE_URL:-http://localhost:${PORT}}"

# If DB_HOST is a container service name (like 'db'), use the internal Postgres port 5432 for DATABASE_URL
if [ "${DB_HOST}" = "db" ] || [ -z "${DB_PORT}" ]; then
  DB_INTERNAL_PORT=5432
else
  DB_INTERNAL_PORT=${DB_PORT}
fi

write_env() {
  local path="$1"
  cat > "$path" <<EOF
# Auto-generated by scripts/generate_env.sh - DO NOT COMMIT
DB_HOST="${DB_HOST}"
DB_PORT="${DB_PORT}"
DB_USER="${DB_USER}"
DB_PASS="${DB_PASS}"
DB_NAME="${DB_NAME}"

  DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_INTERNAL_PORT}/${DB_NAME}?schema=public"

JWT_SECRET="${JWT_SECRET}"
JWT_EXPIRES_IN="${JWT_EXPIRES_IN}"

PORT=${PORT}
HOST="${HOST}"
NODE_ENV="${NODE_ENV}"
LOG_LEVEL="${LOG_LEVEL}"

# Firebase (optional)
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID}"

API_BASE_URL="${API_BASE_URL}"
EOF
  echo "Generated $path"
}

write_env "$BACKEND_ENV_FILE"
write_env "$ROOT_ENV_FILE"

exit 0
#!/usr/bin/env bash
set -euo pipefail

# generate_env.sh
# Generates backend/.env from environment variables on the server.
# Usage: run this script on the VPS after you have set the required environment variables
# Example: export DB_USER=myuser; export DB_PASS=mypass; ./scripts/generate_env.sh

TARGET_BACKEND="./backend/.env"
TARGET_ROOT="./.env"

required() {
  local varname="$1"
  if [ -z "${!varname:-}" ]; then
    echo "ERROR: environment variable '$varname' is not set" >&2
    exit 1
  fi
}

required DB_HOST
required DB_PORT
required DB_USER
required DB_PASS
required DB_NAME
required JWT_SECRET

# Auto-generated by scripts/generate_env.sh - DO NOT COMMIT
DB_HOST="${DB_HOST}"
DB_PORT="${DB_PORT}"
DB_USER="${DB_USER}"
DB_PASS="${DB_PASS}"
DB_NAME="${DB_NAME}"

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"

JWT_SECRET="${JWT_SECRET}"
JWT_EXPIRES_IN="${JWT_EXPIRES_IN:-24h}"

PORT=${PORT:-3000}
HOST="${HOST:-0.0.0.0}"
NODE_ENV="${NODE_ENV:-production}"
LOG_LEVEL="${LOG_LEVEL:-info}"

# Firebase (optional)
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-}"
EOF
echo "Generated $TARGET_BACKEND"

cat > "$TARGET_ROOT" <<EOF
# Auto-generated by scripts/generate_env.sh - DO NOT COMMIT
DB_HOST="${DB_HOST}"
DB_PORT="${DB_PORT}"
DB_USER="${DB_USER}"
DB_PASS="${DB_PASS}"
DB_NAME="${DB_NAME}"

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"

JWT_SECRET="${JWT_SECRET}"
JWT_EXPIRES_IN="${JWT_EXPIRES_IN:-24h}"

PORT=${PORT:-3000}
HOST="${HOST:-0.0.0.0}"
NODE_ENV="${NODE_ENV:-production}"
LOG_LEVEL="${LOG_LEVEL:-info}"

# Firebase (optional)
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-}"
ENV
echo "Generated $TARGET_ROOT"
# Auto-generated by scripts/generate_env.sh - DO NOT COMMIT
DB_HOST="${DB_HOST}"
DB_PORT="${DB_PORT}"
DB_USER="${DB_USER}"
DB_PASS="${DB_PASS}"
DB_NAME="${DB_NAME}"

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"

JWT_SECRET="${JWT_SECRET}"
JWT_EXPIRES_IN="${JWT_EXPIRES_IN:-24h}"

PORT=${PORT:-3000}
HOST="${HOST:-0.0.0.0}"
NODE_ENV="${NODE_ENV:-production}"
LOG_LEVEL="${LOG_LEVEL:-info}"

# Firebase (optional)
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-}"
API_BASE_URL="${API_BASE_URL:-http://localhost:${PORT:-3000}}"
EOF

echo "Generated $TARGET"
